### ISSUE TITLE
No notification and config issue

### ISSUE THREAD

**Issue by ztlevi** [akhramov/org-wild-notifier.el#13]
I was so excited to find this package but unfortunately it seems not working on my machines (Ubuntu 18 and MacOS 14). It might be the problem about my config any my todo samples.

Here is my config:
```
(use-package org-wild-notifier
  :config
  (setq alert-default-style 'libnotify)
  (org-wild-notifier-mode))
```
Once I add `(org-wild-notifier-mode)`, Emacs cannot start cause the `persp-remove-buffer` function is not defined. Even if I requrie persp-mode or `with-eval-after-load` it, it still causes some hash table issue. I don't know how to define it so that I could have it start once my emacs boot up.

What's more, I cannot have any notification on the system. This is my todo sample:
```
* TODO Visit the chocolate factory
SCHEDULED: <2019-01-03 Thu 22:45>
  :PROPERTIES:
  :WILD_NOTIFIER_NOTIFY_BEFORE: 80 60 55 43 15 14 13 12 11 9 8 7 6 5
  :END:
```
Like I said, no notification shows up on my system around 22:35. I tried `org-alert`, sometimes I received some notification but actually I have no idea how that works cuz literally I was receiving past events notifications while no notification for the coming event.

Could you take a look at my issues? It's highly possible because of my config or todo sample issue. But that turns out to be some README documentation problem as well. We probly need a better README for these kind of issues.

Thanks!

**Comment by akhramov** [comment]
Hi, thanks for using this package!

`org-wild-notifier` itself doesn't depend on `persp-mode`. Alas, looks like it doesn't play well with it as well. I will investigate this issue further. 
By any chance, can you have your GNU Emacs configuration shared, so I can use it as reference?

Regarding notifications. Yep, docs are lacking. I will setup notifications on GNU + Linux system and share the configuration as reference. It may take a few days, however. Sorry about that.

Regards

**Comment by ztlevi** [comment]
Thanks!

I am using Doom Emacs. It might be the problem with Doom Emacs. But it's kind of tricky since Doom Emacs comes with tons of packages without persp-mode package issue. Here is my config https://github.com/ztlevi/doom-config/blob/master/+text.el#L41 .

**Comment by ztlevi** [comment]
Here is the solution the Doom's author provides me.
```
(def-package! org-wild-notifier
  :defer t
  :init
  (add-hook 'doom-post-init-hook #'org-wild-notifier-mode t)
  :config
  (setq alert-default-style 'libnotify))
```

`def-package!` is macro of `use-package`. It's kind of weird we are not able to use it without these hacks.

**Comment by ztlevi** [comment]
Hi, I still didn't get how to use this package. How can I get notifications on Linux?

**Comment by akhramov** [comment]
Hi, sorry for making you wait.

A friend of mine managed to receive notifications using `'notifications` backend rather than `'libnotify`.


Can you try the following:

1. Try to retrieve a couple of alerts through `org-wild-notifier`
2. Run `M-x alert--log-open-log`
3. If messages are there, then something's wrong with libnotify (is `notify-send` in `PATH`?)
4. If there are no messages, well... it's a bug with `org-wild-notifier` itself.

**Comment by ztlevi** [comment]
@akhramov Thanks for the help.

I tried the steps above but no luck to get it working...

> Try to retrieve a couple of alerts through org-wild-notifier

The todo example mentioned above is still used for testing.

> Run M-x alert--log-open-log

I couldn't find `alert--log-open-log` function even if I require alert.

> If messages are there, then something's wrong with libnotify (is notify-send in PATH?)

`notify-send` can be found in `PATH` under `/usr/bin/notify-send`. And of course, `/usr/bin` is in the `exec-path`.

**Comment by akhramov** [comment]
@ztlevi  Thank you!
What if you change alert style to `'message`? Would it work?

@neeasade I see you use '`libnotify` as alerts backend as well. Can you please tell us what issues did you have setting up notifications?

**Comment by neeasade** [comment]
I'm afraid I won't have much insight to add here. I use straight.el[1] and my entire alert config is:

```
(use-package alert
  :config (setq alert-default-style
            (if ns/enable-windows-p
              'toaster
              'libnotify
              )))
```

`ns/enable-windows-p` being a toggle in my init.el. I have `notify-send` in my path, and I use dunst[2] to show notifications. Everything pretty pretty mush just worked, I tested with `(alert "test")` when I first installed. 

[1] https://github.com/raxod502/straight.el
[2] https://github.com/dunst-project/dunst

**Comment by akhramov** [comment]
Alright, thanks, @neeasade.

**Comment by ztlevi** [comment]
`message` not working. Let's make a force alert (like `(alert "test")` working first. 

Maybe it's due to the OS version. I tested on MacOS mojave 10.14.2. Let me try Ubuntu 18 tomorrow. Thanks.

**Comment by ztlevi** [comment]
Follow up for OSX, by setting the style to `osx-notifier`, now the alert is showing up in my Mac.

But unfortunately, I still cannot see any notification with the todo below (it's in the `todo.org` file under the root my `org-directory`). I wait for couple minutes at 2019-01-22 Tue 23:25.
```
* TODO Visit the chocolate factory
SCHEDULED: <2019-01-22 Tue 23:40>
  :PROPERTIES:
  :WILD_NOTIFIER_NOTIFY_BEFORE: 80 60 55 43 15 14 13 12 11 9 8 7 6 5
  :END:
```

**Comment by ztlevi** [comment]
Follow up for Linux, `libnotify` works under my Ubuntu 18.

So the rest of the issue is how to define proper todo so that I can get notification form `org-wild-notifier`

**Comment by akhramov** [comment]
Hi, looks like you did nothing wrong.

I managed to retrieve notifications using following org entry:

```
* TODO Visit the chocolate factory
  SCHEDULED: <2019-01-24 Thu 20:34>
  :PROPERTIES:
  :WILD_NOTIFIER_NOTIFY_BEFORE: 80 60 55 43 9 8 7 6 5 4 3 2 1
  :END:
```

By any chance, have you customized `org-wild-notifier-keyword-blacklist` or `org-wild-notifier-keyword-whitelist` variables?

**Comment by ztlevi** [comment]
No, I use the default. And I double-checked my org-agenda. It's listed there.

![image](https://user-images.githubusercontent.com/16655096/51704488-0dfe3b80-1fce-11e9-89f5-7e1aee75a383.png)

**Comment by akhramov** [comment]
@ztlevi I wrote a function which collects debug information. Can you please launch this function and see what's going on in *Messages* buffer?

This function collects information on your current configuration and events processed by library.

```lisp
(defun org-wild-notifier-debug ()
  "Collect debug information for org-wild-notifier"
  (interactive)
  (save-window-excursion
    (let ((org-agenda-use-time-grid nil)
          (org-agenda-compact-blocks t)
          (org-agenda-window-setup 'current-window)
          (org-agenda-buffer-name nil)
          (org-agenda-buffer-tmp-name org-wild-notifier--agenda-buffer-name))

      (org-agenda-list 2)
      (message "registered events: %s \n blacklist: %s \n whitelist: %s \n"
               (org-wild-notifier--retrieve-events)
               org-wild-notifier-keyword-blacklist
               org-wild-notifier-keyword-whitelist)

      (message "filtered events: %s"
               (->> (org-wild-notifier--retrieve-events)
                    (-map 'org-wild-notifier--check-event)))


      (kill-buffer))))
```

Please let me know if you need further assistance

**Comment by ztlevi** [comment]
```
registered events: nil 
 blacklist: nil 
 whitelist: (TODO) 
```
It looks like no event is registered.

**Comment by ztlevi** [comment]
`(org-agenda-list 2)` return the agenda before yesterday. I evaluate this on Jan 25 and get the following:

![image](https://user-images.githubusercontent.com/16655096/51733253-9d8b0500-2035-11e9-8ce2-6b0cef60ec42.png)

**Comment by akhramov** [comment]
Huh, that might be it.

What `(org-agenda-list 2 (org-read-date nil nil "today"))` returns?

**Comment by ztlevi** [comment]
It returns todos from today now. Is this because of the org version?

![image](https://user-images.githubusercontent.com/16655096/51733549-7bde4d80-2036-11e9-86f6-eec85ff2de54.png)

**Comment by akhramov** [comment]
9.1.9 here. What version do you run?

**Comment by akhramov** [comment]
Alright, I have landed the fix. It might take some time for Melpa to update.

Meanwhile you can manually test the fix, by evaluating `org-wild-notifier-check` function:

https://github.com/akhramov/org-wild-notifier.el/blob/master/org-wild-notifier.el#L256-L280

I won't close this issue until your verification, so please go ahead and comment here :)

**Comment by ztlevi** [comment]
Finally get this! Thanks!

![image](https://user-images.githubusercontent.com/16655096/51734360-2192bc00-2039-11e9-8025-b19a33e5fec7.png)

**Comment by akhramov** [comment]
Anytime, thank you!

**Comment by ztlevi** [comment]
Oh, wait. Is there any notification for those schedules without specific time? For example, a schedule on `<2019-01-23 Wed>`, and maybe notify me on the default alert time slot like 10 am.

**Comment by ztlevi** [comment]
Yeah, that would be cool.

**Comment by IsaacDempsey** [comment]
Got this working on MacOS using:

```
  (use-package! org-wild-notifier
    ;; The add-hook enables the mode after init
    :defer t
    :init
    (add-hook 'doom-post-init-hook #'org-wild-notifier-mode t)
    :config
    (setq alert-default-style 'osx-notifier))
```

One question, should this be inside or outside the `(after! org ...)` block?

**Comment by neeasade** [comment]
@IsaacDempsey I would say inside, but I imagine you might get better feedback on the doom-emacs repo.
