### ISSUE TITLE
Missing agenda files hang org-wild-notifier

### ISSUE THREAD

**Issue by OverkillGuy** [akhramov/org-wild-notifier.el#23]
The following is not quite an issue in `org-wild-notifier` itself, but a weird interaction between Org mode and this package's use of `async`. Noted here so that others may know about this issue without having to troubleshoot like I did.

`org-wild-notifier-check` hangs emacs when Org agenda prompts for interactive input. In my case this is due to moving an org file around that was listed in `org-agenda-file`, which causes next `org-agenda` invocation to prompt for input to remove the missing file from agenda list.

Reproduction:
- Tweak `org-agenda-files` to add a non-existent file (`~/org/non_existent_file.org`)
- Run `org-wild-notifier-check` (such as toggling on `org-wild-notifier-mode`)

Expected behaviour: Function returns and control is returned to emacs?

Buggy behaviour: Emacs hangs trying to evaluate `org-agenda` in `async-sandbox` as per https://github.com/akhramov/org-wild-notifier.el/blob/db143f812ed65f5ab6c75d0d686b73da20300b32/org-wild-notifier.el#L234

Explanation: The `async` call to `org-agenda` makes it so the prompt is never visible to user, so it isn't clear the user needs to do something. The function never returns, and hangs emacs altogether.

Workaround: Ensure you can run `org-agenda` without interactive input. For me this was running it manually (`C-c C-a`), responding to input (yes, remove file from list), and problem is gone.

As mentioned, this issue is mostly unexpected interactions between packages, but it does surprise users (my config was just hanging on load, which I traced to my use-package invocation of the notifier). 
It might warrant further examination to search for other cases where org mode might prompt for input causing such a hanging.

I'm absolutely OK with package author closing this issue immediately without further action, I just want to log what's wrong for the poor souls out there who like me were puzzled. Thanks again for a great package!

**Comment by akhramov** [comment]
Alright, thanks again for the exceptional bug report and I am sorry for the delay!

This should be resolved in v0.3.1 and should be available shortly on Melpa.
