### ISSUE TITLE
missing org-version.el issue

### ISSUE THREAD

**Issue by ztlevi** [akhramov/org-wild-notifier.el#29]
Missing file for new org mode.

```
error in process sentinel: async-handle-result: Cannot open load file: No such file or directory, org-version.el
error in process sentinel: Cannot open load file: No such file or directory, org-version.el
```

Org version: 9.3, emacs version 26.3

**Comment by akhramov** [comment]
That’s strange indeed. Thanks for report!

Can you please tell me the output of the following command:

M-x org-version

**Comment by ztlevi** [comment]
It’s 9.3

**Comment by akhramov** [comment]
Huh, sounds like there's something with your configuration.

A quick search lead me to the doom-emacs issue. Please try the workarounds proposed there:
https://github.com/hlissner/doom-emacs/issues/2010#issuecomment-549228610
