### ISSUE TITLE
Allow for multiple alert times for all entries

### ISSUE THREAD

**Issue by newageoflight** [akhramov/org-wild-notifier.el#32]
Would it be possible to have something like WILD_NOTIFIER_NOTIFY_BEFORE as a global property (rather than having to type it in on every agenda entry)? i.e. have all deadlines produce a notification e.g. 720, 120 and 20 minutes prior

**Comment by akhramov** [comment]
Neat, great idea. The new version is rolled out. Give MELPA some time to update its bases. 

You will have to customize `org-wild-notifier-alert-time` variable, e.g. `(setf org-wild-notifier-alert-time '(720 120 20))` to achieve what was described.

Don't hesitate commenting here if something goes wrong.
