### ISSUE TITLE
Notify ignore whitelist value and only show TODO

### ISSUE THREAD

**Issue by mohammadanton** [akhramov/org-wild-notifier.el#34]
I already change org-wild-notifier-keyword-whitelist to ("READ")
but it ignore it

when I try org-wild-notifier-check, it show nothing.
org-wild-check only show notif for task with "TODO" keyword

**Comment by akhramov** [comment]
Hey there. Please double-check that you have customized the `org-todo-keywords` variable, so READ is being recognized as a keyword

**Comment by mohammadanton** [comment]
I think my emacs config have some error.
I try set another variable and didn't work although it change.

Sorrry, I think this is not org-wild-notifier bug.

**Comment by akhramov** [comment]
No problem, please reopen this issue if the error persists.
