### ISSUE TITLE
Add a default alert time option for scheduled items without a time

### ISSUE THREAD

**Issue by mtreca** [akhramov/org-wild-notifier.el#36]
I just found your package and it's pretty great.

After reading through the issues, you mentioned in issue #13 that it would be nice to add an option to customize at which time scheduled items without a specific time are reminded (as you said, they display by default at 23:50).

What would be even better IMO is the option to display these "default" items at multiple times during the day using something like this `(setq org-wild-notifier-default-task-alert-time '(08:00 12:00 16:00))`.

**Comment by akhramov** [comment]
Neat, I like the feature. Thanks for filling in the request.

**Comment by colonelpanic8** [comment]
@mtreca org-wild-notifier-day-wide-alert-times does what you want. Added in d8f91db38a9cf3dc5551968b2e0bb4378a186b36
