### ISSUE TITLE
notifications for timestamped items 

### ISSUE THREAD

**Issue by tiktaaliki** [akhramov/org-wild-notifier.el#37]
Hi, thanks for this package!

Based on issue #3 and issue #35, I gather that it should be possible to get notifications for entries with timestamps but without TODO keywords, as long as the whitelist is blank. 

This does NOT produce any alerts
* wild notifier testing
<2020-07-19 Sun 10:03>

This DOES produce an alert
* TODO wild notifier testing
<2020-07-19 Sun 10:03>

I mainly want to use this with my calendar events, which do not have TODOs on them and are just timestamped (no SCHEDULED or DEADLINE keywords either). Is this possible with your package, or is a current limitation?

thanks!

**Comment by akhramov** [comment]
Hello there, thanks for the example.

The desired behavior should be achievable with the package.  

I created [a test case](https://github.com/akhramov/org-wild-notifier.el/pull/38/files) based on your example. Alas, the test is green.

What it does is just sets `org-wild-notifier-keyword-whitelist` to nil.

 I know how it sounds, but may I ask you to double-check the value of `org-wild-notifier-keyword-whitelist`?

**Comment by tiktaaliki** [comment]
Hi, thanks for the response! 
The whitelist is indeed set to nil:
`org-wild-notifier-keyword-whitelist is a variable defined in ‘org-wild-notifier.el’.
Its value is nil
Original value was ("TODO")`
It may be a problem of something else in my configuration working agianst it? i'll try and troubleshoot. good to know that it should be working that way. thanks!

**Comment by akhramov** [comment]
Yeah, I see you have your config published to github.

I will pull it and try to repro the issue locally.

**Comment by tiktaaliki** [comment]
ok, if it is simple, thanks! but if the issue is not readily apparent, don't worry about spending too much energy on it...!

**Comment by akhramov** [comment]
#38 should fix this. Thanks! 

If it's still broken, please re-open the issue.
