### ISSUE TITLE
Put absolute time in message

### ISSUE THREAD

**Issue by jcguu95** [akhramov/org-wild-notifier.el#43]
I like your package very much. Thank you!

How would you add an absolute time in the message. For example, instead of

> Have breakfast in 10 minutes!

display 

> Have breakfast at 06:50am (in 10 minutes)!

This can be useful for users who wish the message to persist. In that case, while coming back to the screen, the user would wonder when the message was displayed.

---

I'm learning elisp. So if you could point out specific variables to look at, I can customize it.. or even make a pull request. Thank you!

**Comment by colonelpanic8** [comment]
There is now org-wild-notifier-display-time-format-string which you can use to get the time in any format thatyou want.
