### ISSUE TITLE
Update to allow installation

### ISSUE THREAD

**Issue by appetrosyan** [akhramov/org-wild-notifier.el#5]
PLease update such that it can be used with modern org. , 

otherwise gives the error 
```
Failed to install org-wild-notifier: Package ‘org-8.0’ is unavailable
```

**Comment by akhramov** [comment]
Thanks for the report, I'm working on it.

**Comment by akhramov** [comment]
`v0.2.3` should fix our problem. It might take some time till the package makes it to Melpa. Feel free to reopen this issue if you encounter further problem with installation.

**Comment by appetrosyan** [comment]
Cheers!
