### ISSUE TITLE
TODOs with custom defined keywords are not notified

### ISSUE THREAD

**Issue by bymoz089** [akhramov/org-wild-notifier.el#55]
**The issue is**: custom TODO items (like `MEET` in below example) are not notified about.        
(Is something like this supported at all?)

---

**Example:**       
Org-mode [allows to configure custom keywords for TODOs](https://orgmode.org/manual/TODO-types.html). Creating a `MEET` TODO keyword for meetings, is done like so:

    (setq org-todo-keywords '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(v!)" )
                              (type "MEET(M)" "|" "OVER(V)" "CNCL(X@)")))

Now in the *task list*, there are some meetings, the user should be notified about:

    ** MEET a meeting w/o SCHEDULED
    <2022-07-13 Wed 13:00>
    ** MEET a meeting with SCHEDULED
    SCHEDULED: <2022-07-13 Wed 13:05>
    
Therefore `org-wild-notifier-keyword-whitelist` has been set up like the following:

    (setq org-wild-notifier-keyword-whitelist '("MEET" "TODO"))

But no notifications are showing up.      
When replacing `MEET` with `TODO` in the above *task list*, then notifications are shown as expected.
Setup of org-wild-notifier.el is correct, since standard TODO items work as expected here.

**Comment by colonelpanic8** [comment]
I think you can just set org-wild-notifier-keyword-whitelist nil

**Comment by colonelpanic8** [comment]
Pulling in the org-todo-keywords into the notifier process seems to have worked.
