### ISSUE TITLE
error in process sentinel: async-handle-result: Wrong type argument: integer-or-marker-p

### ISSUE THREAD

**Issue by bcc32** [akhramov/org-wild-notifier.el#59]
After the recent updates (#56, #57), I'm getting errors that look like the following showing up in my `*Messages*` buffer every minute:

```
error in process sentinel: async-handle-result: Wrong type argument: integer-or-marker-p, (("CATEGORY" . "todo") ("EFFORT" . "0:15") ("LAST_REPEAT" . "[2022-10-25 Tue 11:08]") ("STYLE" . "habit") ("TIMESTAMP_IA" . "[2022-10-25 Tue 11:08]") ("SCHEDULED" . "<2022-10-26 Wed .+1d>") ("BLOCKED" . "") ("FILE" . "...") ("PRIORITY" . "B") ("TODO" . "TODO") ("ITEM" . "..."))
```

FWIW, I configure org-wild-notifier through Spacemacs, whose configuration looks like:

```elisp
(defun org/init-org-wild-notifier ()
  (use-package org-wild-notifier
    :defer t
    :init
    (when org-start-notification-daemon-on-startup
      (org-wild-notifier-mode))))
```

So I don't think Spacemacs is doing anything unusual here.

@nshi, curious if you know off-hand what the issue might be, otherwise I can look into it a bit deeper.

**Comment by nshi** [comment]
@bcc32, sorry for the inconvenience. I've seen this error before when some part of the package is evaluated but not the rest. Did you reload the package or restart emacs after upgrading? If might be worth trying restarting. If you have daemon running, `kill-emacs` might be needed.
