### ISSUE TITLE
Don't gather item with a raw date

### ISSUE THREAD

**Issue by galaunay** [akhramov/org-wild-notifier.el#7]
I cannot get `org-wild-notifier` to capture the entries associated with a raw date, e.g.:
```
*** TODO Really important thing to do
     <2018-02-20 Tue 20:24>
```

It does work perfectly with a scheduled or deadline entry.
Is this an expected behavior ?

**Comment by akhramov** [comment]
Hi, thank you.
It's expected, but has to be changed for sure.

I will investigate further, but here's the code responsible for the current behavior:
https://github.com/akhramov/org-wild-notifier.el/blob/master/org-wild-notifier.el#L199-L209

**Comment by galaunay** [comment]
It was easier to fix than expected.
I will try to update the tests as well.

**Comment by akhramov** [comment]
Thank you very much for looking into this!
