### ISSUE TITLE
alert-fade-time when using the builtin 'notifications package - how to change amount of time notifications are displayed?

### ISSUE THREAD

**Issue by danielkrajnik** [akhramov/org-wild-notifier.el#70]
Is there any way to change how long notifications will be displayed when using the builtin 'notifications for `alert-default-style`? alert-fade-time doesn't seem to work (it works with libnotify option).

**Comment by danielkrajnik** [comment]
sorry, it turns out that this variable only works when you set `(setq alert-default-style 'libnotify)`  (of course)

**Comment by colonelpanic8** [comment]
@danielkrajnik i believe this is more of an alert.el question than anything that relates to og-wild-notifier.
